Repository Jason2426/your-tribe-for-life-squad-page, pull requests merged in 2024-09, with the labels that each got.

#13 Squad logo component made and added responsiveness.
  src/components /dropdown-menu.svelte
  src/components /squad-logo.svelte
  src/routes/+page.svelte
Labels: component

#14 10 detail-page bouwen v1
  src/component detailpage/carousel.svelte
  src/component detailpage/details.svelte
  src/routes/+page.svelte
  src/routes/test-page/+page.svelte
Labels: component

#20 6-Topbar component
  src/components/topbar.svelte
  src/routes/+page.svelte
Labels: component

#37 First section grid & subtle animation
  src/routes/+page.svelte
  src/styles/fonts.css
  src/styles/global.css
  src/styles/intro-section.css
  static/fonts/ARIALROUNDEDMT.TTF
  static/fonts/ARIALROUNDEDMTEXTRABOLD.TTF
  static/images/image.png
Labels: component, Iteration 2

#44 Fix : Card component adjusted to grid layout
  src/lib/card-component.svelte
  src/routes/+page.svelte
  src/styles/intro-section.css
Labels: fix

#51 grid aangepast naar afbeelding op Github
  src/styles/grid.css
Labels: component, fix

#52 Unnecessary file removal
  tests/test.js
Labels: Iteration 2, fix

#53 Unnecessary file removal v2
  src/app.d.ts
  src/index.test.js
Labels: Iteration 2, fix

#63 31 iteration 2 bouwen style detail component for new design
  src/lib/card-component.svelte
  src/lib/details.svelte
  src/routes/+page.svelte
  src/styles/deail.css
  src/styles/global.css
  src/styles/intro-section.css
  src/styles/meet-our-team.css
Labels: enhancement, component, Iteration 2, fix, Could haves

#69 29 iteration 2 bouwen layout card images bouwen second section
  src/routes/+page.svelte
  src/styles/global.css
  src/styles/intro-section.css
  src/styles/meet-our-team.css
Labels: component, fix
